<<<<<<< HEAD
// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
=======
// Code generated by protoc-gen-go. DO NOT EDIT.
>>>>>>> upstream/master
// source: dapr/proto/runtime/v1/appcallback.proto

package runtime

import (
	context "context"
<<<<<<< HEAD
=======
	fmt "fmt"
>>>>>>> upstream/master
	v1 "github.com/dapr/go-sdk/dapr/proto/common/v1"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
<<<<<<< HEAD
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4
=======
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package
>>>>>>> upstream/master

// BindingEventConcurrency is the kind of concurrency
type BindingEventResponse_BindingEventConcurrency int32

const (
	// SEQUENTIAL sends data to output bindings specified in "to" sequentially.
	BindingEventResponse_SEQUENTIAL BindingEventResponse_BindingEventConcurrency = 0
	// PARALLEL sends data to output bindings specified in "to" in parallel.
	BindingEventResponse_PARALLEL BindingEventResponse_BindingEventConcurrency = 1
)

<<<<<<< HEAD
// Enum value maps for BindingEventResponse_BindingEventConcurrency.
var (
	BindingEventResponse_BindingEventConcurrency_name = map[int32]string{
		0: "SEQUENTIAL",
		1: "PARALLEL",
	}
	BindingEventResponse_BindingEventConcurrency_value = map[string]int32{
		"SEQUENTIAL": 0,
		"PARALLEL":   1,
	}
)

func (x BindingEventResponse_BindingEventConcurrency) Enum() *BindingEventResponse_BindingEventConcurrency {
	p := new(BindingEventResponse_BindingEventConcurrency)
	*p = x
	return p
}

func (x BindingEventResponse_BindingEventConcurrency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingEventResponse_BindingEventConcurrency) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_runtime_v1_appcallback_proto_enumTypes[0].Descriptor()
}

func (BindingEventResponse_BindingEventConcurrency) Type() protoreflect.EnumType {
	return &file_dapr_proto_runtime_v1_appcallback_proto_enumTypes[0]
}

func (x BindingEventResponse_BindingEventConcurrency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingEventResponse_BindingEventConcurrency.Descriptor instead.
func (BindingEventResponse_BindingEventConcurrency) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{2, 0}
=======
var BindingEventResponse_BindingEventConcurrency_name = map[int32]string{
	0: "SEQUENTIAL",
	1: "PARALLEL",
}

var BindingEventResponse_BindingEventConcurrency_value = map[string]int32{
	"SEQUENTIAL": 0,
	"PARALLEL":   1,
}

func (x BindingEventResponse_BindingEventConcurrency) String() string {
	return proto.EnumName(BindingEventResponse_BindingEventConcurrency_name, int32(x))
}

func (BindingEventResponse_BindingEventConcurrency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{2, 0}
>>>>>>> upstream/master
}

// TopicEventRequest message is compatiable with CloudEvent spec v1.0
// https://github.com/cloudevents/spec/blob/v1.0/spec.md
type TopicEventRequest struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

=======
>>>>>>> upstream/master
	// id identifies the event. Producers MUST ensure that source + id
	// is unique for each distinct event. If a duplicate event is re-sent
	// (e.g. due to a network error) it MAY have the same id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// source identifies the context in which an event happened.
	// Often this will include information such as the type of the
	// event source, the organization publishing the event or the process
	// that produced the event. The exact syntax and semantics behind
	// the data encoded in the URI is defined by the event producer.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The type of event related to the originating occurrence.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// The version of the CloudEvents specification.
	SpecVersion string `protobuf:"bytes,4,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	// The content type of data value.
	DataContentType string `protobuf:"bytes,5,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	// The content of the event.
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	// The pubsub topic which publisher sent to.
<<<<<<< HEAD
	Topic string `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *TopicEventRequest) Reset() {
	*x = TopicEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicEventRequest) ProtoMessage() {}

func (x *TopicEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicEventRequest.ProtoReflect.Descriptor instead.
func (*TopicEventRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{0}
}

func (x *TopicEventRequest) GetId() string {
	if x != nil {
		return x.Id
=======
	Topic                string   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicEventRequest) Reset()         { *m = TopicEventRequest{} }
func (m *TopicEventRequest) String() string { return proto.CompactTextString(m) }
func (*TopicEventRequest) ProtoMessage()    {}
func (*TopicEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{0}
}

func (m *TopicEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicEventRequest.Unmarshal(m, b)
}
func (m *TopicEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicEventRequest.Marshal(b, m, deterministic)
}
func (m *TopicEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicEventRequest.Merge(m, src)
}
func (m *TopicEventRequest) XXX_Size() int {
	return xxx_messageInfo_TopicEventRequest.Size(m)
}
func (m *TopicEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicEventRequest proto.InternalMessageInfo

func (m *TopicEventRequest) GetId() string {
	if m != nil {
		return m.Id
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetSource() string {
	if x != nil {
		return x.Source
=======
func (m *TopicEventRequest) GetSource() string {
	if m != nil {
		return m.Source
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetType() string {
	if x != nil {
		return x.Type
=======
func (m *TopicEventRequest) GetType() string {
	if m != nil {
		return m.Type
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
=======
func (m *TopicEventRequest) GetSpecVersion() string {
	if m != nil {
		return m.SpecVersion
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
=======
func (m *TopicEventRequest) GetDataContentType() string {
	if m != nil {
		return m.DataContentType
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
=======
func (m *TopicEventRequest) GetData() []byte {
	if m != nil {
		return m.Data
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
func (x *TopicEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
=======
func (m *TopicEventRequest) GetTopic() string {
	if m != nil {
		return m.Topic
>>>>>>> upstream/master
	}
	return ""
}

// BindingEventRequest represents input bindings event.
type BindingEventRequest struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

=======
>>>>>>> upstream/master
	// Requried. The name of the input binding component.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The payload that the input bindings sent
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The metadata set by the input binging components.
<<<<<<< HEAD
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BindingEventRequest) Reset() {
	*x = BindingEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingEventRequest) ProtoMessage() {}

func (x *BindingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingEventRequest.ProtoReflect.Descriptor instead.
func (*BindingEventRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{1}
}

func (x *BindingEventRequest) GetName() string {
	if x != nil {
		return x.Name
=======
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BindingEventRequest) Reset()         { *m = BindingEventRequest{} }
func (m *BindingEventRequest) String() string { return proto.CompactTextString(m) }
func (*BindingEventRequest) ProtoMessage()    {}
func (*BindingEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{1}
}

func (m *BindingEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingEventRequest.Unmarshal(m, b)
}
func (m *BindingEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingEventRequest.Marshal(b, m, deterministic)
}
func (m *BindingEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingEventRequest.Merge(m, src)
}
func (m *BindingEventRequest) XXX_Size() int {
	return xxx_messageInfo_BindingEventRequest.Size(m)
}
func (m *BindingEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindingEventRequest proto.InternalMessageInfo

func (m *BindingEventRequest) GetName() string {
	if m != nil {
		return m.Name
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *BindingEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
=======
func (m *BindingEventRequest) GetData() []byte {
	if m != nil {
		return m.Data
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
func (x *BindingEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
=======
func (m *BindingEventRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
>>>>>>> upstream/master
	}
	return nil
}

// BindingEventResponse includes operations to save state or
// send data to output bindings optionally.
type BindingEventResponse struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of state store where states are saved.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The state key values which will be stored in store_name.
	States []*v1.StateItem `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
=======
	// The name of state store where states are saved.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The state key values which will be stored in store_name.
	States []*v1.StateSaveRequest `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
>>>>>>> upstream/master
	// The list of output bindings.
	To []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	// The content which will be sent to "to" output bindings.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The concurrency of output bindings to send data to
	// "to" output bindings list. The default is SEQUENTIAL.
<<<<<<< HEAD
	Concurrency BindingEventResponse_BindingEventConcurrency `protobuf:"varint,5,opt,name=concurrency,proto3,enum=dapr.proto.runtime.v1.BindingEventResponse_BindingEventConcurrency" json:"concurrency,omitempty"`
}

func (x *BindingEventResponse) Reset() {
	*x = BindingEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingEventResponse) ProtoMessage() {}

func (x *BindingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingEventResponse.ProtoReflect.Descriptor instead.
func (*BindingEventResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{2}
}

func (x *BindingEventResponse) GetStoreName() string {
	if x != nil {
		return x.StoreName
=======
	Concurrency          BindingEventResponse_BindingEventConcurrency `protobuf:"varint,5,opt,name=concurrency,proto3,enum=dapr.proto.runtime.v1.BindingEventResponse_BindingEventConcurrency" json:"concurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *BindingEventResponse) Reset()         { *m = BindingEventResponse{} }
func (m *BindingEventResponse) String() string { return proto.CompactTextString(m) }
func (*BindingEventResponse) ProtoMessage()    {}
func (*BindingEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{2}
}

func (m *BindingEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingEventResponse.Unmarshal(m, b)
}
func (m *BindingEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingEventResponse.Marshal(b, m, deterministic)
}
func (m *BindingEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingEventResponse.Merge(m, src)
}
func (m *BindingEventResponse) XXX_Size() int {
	return xxx_messageInfo_BindingEventResponse.Size(m)
}
func (m *BindingEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindingEventResponse proto.InternalMessageInfo

func (m *BindingEventResponse) GetStoreName() string {
	if m != nil {
		return m.StoreName
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *BindingEventResponse) GetStates() []*v1.StateItem {
	if x != nil {
		return x.States
=======
func (m *BindingEventResponse) GetStates() []*v1.StateSaveRequest {
	if m != nil {
		return m.States
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
func (x *BindingEventResponse) GetTo() []string {
	if x != nil {
		return x.To
=======
func (m *BindingEventResponse) GetTo() []string {
	if m != nil {
		return m.To
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
func (x *BindingEventResponse) GetData() []byte {
	if x != nil {
		return x.Data
=======
func (m *BindingEventResponse) GetData() []byte {
	if m != nil {
		return m.Data
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
func (x *BindingEventResponse) GetConcurrency() BindingEventResponse_BindingEventConcurrency {
	if x != nil {
		return x.Concurrency
=======
func (m *BindingEventResponse) GetConcurrency() BindingEventResponse_BindingEventConcurrency {
	if m != nil {
		return m.Concurrency
>>>>>>> upstream/master
	}
	return BindingEventResponse_SEQUENTIAL
}

// ListTopicSubscriptionsResponse is the message including the list of the subscribing topics.
type ListTopicSubscriptionsResponse struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of topics.
	Subscriptions []*TopicSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *ListTopicSubscriptionsResponse) Reset() {
	*x = ListTopicSubscriptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopicSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicSubscriptionsResponse) ProtoMessage() {}

func (x *ListTopicSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{3}
}

func (x *ListTopicSubscriptionsResponse) GetSubscriptions() []*TopicSubscription {
	if x != nil {
		return x.Subscriptions
=======
	// The list of topics.
	Subscriptions        []*TopicSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListTopicSubscriptionsResponse) Reset()         { *m = ListTopicSubscriptionsResponse{} }
func (m *ListTopicSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTopicSubscriptionsResponse) ProtoMessage()    {}
func (*ListTopicSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{3}
}

func (m *ListTopicSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListTopicSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListTopicSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicSubscriptionsResponse.Merge(m, src)
}
func (m *ListTopicSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTopicSubscriptionsResponse.Size(m)
}
func (m *ListTopicSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicSubscriptionsResponse proto.InternalMessageInfo

func (m *ListTopicSubscriptionsResponse) GetSubscriptions() []*TopicSubscription {
	if m != nil {
		return m.Subscriptions
>>>>>>> upstream/master
	}
	return nil
}

// TopicSubscription represents topic and metadata.
type TopicSubscription struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The name of topic which will be subscribed
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// The optional properties used for this topic's subscribtion e.g. session id
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TopicSubscription) Reset() {
	*x = TopicSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSubscription) ProtoMessage() {}

func (x *TopicSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSubscription.ProtoReflect.Descriptor instead.
func (*TopicSubscription) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{4}
}

func (x *TopicSubscription) GetTopic() string {
	if x != nil {
		return x.Topic
=======
	// The name of topic which will be subscribed
	Topic                string            `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TopicSubscription) Reset()         { *m = TopicSubscription{} }
func (m *TopicSubscription) String() string { return proto.CompactTextString(m) }
func (*TopicSubscription) ProtoMessage()    {}
func (*TopicSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{4}
}

func (m *TopicSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicSubscription.Unmarshal(m, b)
}
func (m *TopicSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicSubscription.Marshal(b, m, deterministic)
}
func (m *TopicSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicSubscription.Merge(m, src)
}
func (m *TopicSubscription) XXX_Size() int {
	return xxx_messageInfo_TopicSubscription.Size(m)
}
func (m *TopicSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_TopicSubscription proto.InternalMessageInfo

func (m *TopicSubscription) GetTopic() string {
	if m != nil {
		return m.Topic
>>>>>>> upstream/master
	}
	return ""
}

<<<<<<< HEAD
func (x *TopicSubscription) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
=======
func (m *TopicSubscription) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
>>>>>>> upstream/master
	}
	return nil
}

// ListInputBindingsResponse is the message including the list of input bindings.
type ListInputBindingsResponse struct {
<<<<<<< HEAD
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of input bindings.
	Bindings []string `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
}

func (x *ListInputBindingsResponse) Reset() {
	*x = ListInputBindingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInputBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInputBindingsResponse) ProtoMessage() {}

func (x *ListInputBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInputBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListInputBindingsResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP(), []int{5}
}

func (x *ListInputBindingsResponse) GetBindings() []string {
	if x != nil {
		return x.Bindings
=======
	// The list of input bindings.
	Bindings             []string `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInputBindingsResponse) Reset()         { *m = ListInputBindingsResponse{} }
func (m *ListInputBindingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListInputBindingsResponse) ProtoMessage()    {}
func (*ListInputBindingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_830251cb323c018d, []int{5}
}

func (m *ListInputBindingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInputBindingsResponse.Unmarshal(m, b)
}
func (m *ListInputBindingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInputBindingsResponse.Marshal(b, m, deterministic)
}
func (m *ListInputBindingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInputBindingsResponse.Merge(m, src)
}
func (m *ListInputBindingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListInputBindingsResponse.Size(m)
}
func (m *ListInputBindingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInputBindingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListInputBindingsResponse proto.InternalMessageInfo

func (m *ListInputBindingsResponse) GetBindings() []string {
	if m != nil {
		return m.Bindings
>>>>>>> upstream/master
	}
	return nil
}

<<<<<<< HEAD
var File_dapr_proto_runtime_v1_appcallback_proto protoreflect.FileDescriptor

var file_dapr_proto_runtime_v1_appcallback_proto_rawDesc = []byte{
	0x0a, 0x27, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x64,
	0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc8, 0x01, 0x0a, 0x11, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0xd0, 0x01, 0x0a, 0x13,
	0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x54, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb2,
	0x02, 0x0a, 0x14, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x65, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x43, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x37, 0x0a, 0x17, 0x42, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x51, 0x55, 0x45, 0x4e, 0x54,
	0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x52, 0x41, 0x4c, 0x4c, 0x45,
	0x4c, 0x10, 0x01, 0x22, 0x70, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64,
	0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x11, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x52, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x37, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x32, 0xf3, 0x03, 0x0a, 0x0b,
	0x41, 0x70, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x57, 0x0a, 0x08, 0x4f,
	0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x23, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64,
	0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x35, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x52, 0x0a, 0x0c, 0x4f, 0x6e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x28, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x30, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x0e, 0x4f, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x7c, 0x0a, 0x0a, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x76, 0x31, 0x42,
	0x15, 0x44, 0x61, 0x70, 0x72, 0x41, 0x70, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x64,
	0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0xaa, 0x02, 0x20, 0x44,
	0x61, 0x70, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x2e,
	0x41, 0x75, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dapr_proto_runtime_v1_appcallback_proto_rawDescOnce sync.Once
	file_dapr_proto_runtime_v1_appcallback_proto_rawDescData = file_dapr_proto_runtime_v1_appcallback_proto_rawDesc
)

func file_dapr_proto_runtime_v1_appcallback_proto_rawDescGZIP() []byte {
	file_dapr_proto_runtime_v1_appcallback_proto_rawDescOnce.Do(func() {
		file_dapr_proto_runtime_v1_appcallback_proto_rawDescData = protoimpl.X.CompressGZIP(file_dapr_proto_runtime_v1_appcallback_proto_rawDescData)
	})
	return file_dapr_proto_runtime_v1_appcallback_proto_rawDescData
}

var file_dapr_proto_runtime_v1_appcallback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dapr_proto_runtime_v1_appcallback_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dapr_proto_runtime_v1_appcallback_proto_goTypes = []interface{}{
	(BindingEventResponse_BindingEventConcurrency)(0), // 0: dapr.proto.runtime.v1.BindingEventResponse.BindingEventConcurrency
	(*TopicEventRequest)(nil),                         // 1: dapr.proto.runtime.v1.TopicEventRequest
	(*BindingEventRequest)(nil),                       // 2: dapr.proto.runtime.v1.BindingEventRequest
	(*BindingEventResponse)(nil),                      // 3: dapr.proto.runtime.v1.BindingEventResponse
	(*ListTopicSubscriptionsResponse)(nil),            // 4: dapr.proto.runtime.v1.ListTopicSubscriptionsResponse
	(*TopicSubscription)(nil),                         // 5: dapr.proto.runtime.v1.TopicSubscription
	(*ListInputBindingsResponse)(nil),                 // 6: dapr.proto.runtime.v1.ListInputBindingsResponse
	nil,                                               // 7: dapr.proto.runtime.v1.BindingEventRequest.MetadataEntry
	nil,                                               // 8: dapr.proto.runtime.v1.TopicSubscription.MetadataEntry
	(*v1.StateItem)(nil),                              // 9: dapr.proto.common.v1.StateItem
	(*v1.InvokeRequest)(nil),                          // 10: dapr.proto.common.v1.InvokeRequest
	(*empty.Empty)(nil),                               // 11: google.protobuf.Empty
	(*v1.InvokeResponse)(nil),                         // 12: dapr.proto.common.v1.InvokeResponse
}
var file_dapr_proto_runtime_v1_appcallback_proto_depIdxs = []int32{
	7,  // 0: dapr.proto.runtime.v1.BindingEventRequest.metadata:type_name -> dapr.proto.runtime.v1.BindingEventRequest.MetadataEntry
	9,  // 1: dapr.proto.runtime.v1.BindingEventResponse.states:type_name -> dapr.proto.common.v1.StateItem
	0,  // 2: dapr.proto.runtime.v1.BindingEventResponse.concurrency:type_name -> dapr.proto.runtime.v1.BindingEventResponse.BindingEventConcurrency
	5,  // 3: dapr.proto.runtime.v1.ListTopicSubscriptionsResponse.subscriptions:type_name -> dapr.proto.runtime.v1.TopicSubscription
	8,  // 4: dapr.proto.runtime.v1.TopicSubscription.metadata:type_name -> dapr.proto.runtime.v1.TopicSubscription.MetadataEntry
	10, // 5: dapr.proto.runtime.v1.AppCallback.OnInvoke:input_type -> dapr.proto.common.v1.InvokeRequest
	11, // 6: dapr.proto.runtime.v1.AppCallback.ListTopicSubscriptions:input_type -> google.protobuf.Empty
	1,  // 7: dapr.proto.runtime.v1.AppCallback.OnTopicEvent:input_type -> dapr.proto.runtime.v1.TopicEventRequest
	11, // 8: dapr.proto.runtime.v1.AppCallback.ListInputBindings:input_type -> google.protobuf.Empty
	2,  // 9: dapr.proto.runtime.v1.AppCallback.OnBindingEvent:input_type -> dapr.proto.runtime.v1.BindingEventRequest
	12, // 10: dapr.proto.runtime.v1.AppCallback.OnInvoke:output_type -> dapr.proto.common.v1.InvokeResponse
	4,  // 11: dapr.proto.runtime.v1.AppCallback.ListTopicSubscriptions:output_type -> dapr.proto.runtime.v1.ListTopicSubscriptionsResponse
	11, // 12: dapr.proto.runtime.v1.AppCallback.OnTopicEvent:output_type -> google.protobuf.Empty
	6,  // 13: dapr.proto.runtime.v1.AppCallback.ListInputBindings:output_type -> dapr.proto.runtime.v1.ListInputBindingsResponse
	3,  // 14: dapr.proto.runtime.v1.AppCallback.OnBindingEvent:output_type -> dapr.proto.runtime.v1.BindingEventResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dapr_proto_runtime_v1_appcallback_proto_init() }
func file_dapr_proto_runtime_v1_appcallback_proto_init() {
	if File_dapr_proto_runtime_v1_appcallback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTopicSubscriptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_runtime_v1_appcallback_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInputBindingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dapr_proto_runtime_v1_appcallback_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapr_proto_runtime_v1_appcallback_proto_goTypes,
		DependencyIndexes: file_dapr_proto_runtime_v1_appcallback_proto_depIdxs,
		EnumInfos:         file_dapr_proto_runtime_v1_appcallback_proto_enumTypes,
		MessageInfos:      file_dapr_proto_runtime_v1_appcallback_proto_msgTypes,
	}.Build()
	File_dapr_proto_runtime_v1_appcallback_proto = out.File
	file_dapr_proto_runtime_v1_appcallback_proto_rawDesc = nil
	file_dapr_proto_runtime_v1_appcallback_proto_goTypes = nil
	file_dapr_proto_runtime_v1_appcallback_proto_depIdxs = nil
=======
func init() {
	proto.RegisterEnum("dapr.proto.runtime.v1.BindingEventResponse_BindingEventConcurrency", BindingEventResponse_BindingEventConcurrency_name, BindingEventResponse_BindingEventConcurrency_value)
	proto.RegisterType((*TopicEventRequest)(nil), "dapr.proto.runtime.v1.TopicEventRequest")
	proto.RegisterType((*BindingEventRequest)(nil), "dapr.proto.runtime.v1.BindingEventRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.BindingEventRequest.MetadataEntry")
	proto.RegisterType((*BindingEventResponse)(nil), "dapr.proto.runtime.v1.BindingEventResponse")
	proto.RegisterType((*ListTopicSubscriptionsResponse)(nil), "dapr.proto.runtime.v1.ListTopicSubscriptionsResponse")
	proto.RegisterType((*TopicSubscription)(nil), "dapr.proto.runtime.v1.TopicSubscription")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.TopicSubscription.MetadataEntry")
	proto.RegisterType((*ListInputBindingsResponse)(nil), "dapr.proto.runtime.v1.ListInputBindingsResponse")
}

func init() {
	proto.RegisterFile("dapr/proto/runtime/v1/appcallback.proto", fileDescriptor_830251cb323c018d)
}

var fileDescriptor_830251cb323c018d = []byte{
	// 751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xef, 0x6e, 0x12, 0x41,
	0x10, 0xe7, 0x0e, 0x8a, 0x30, 0x50, 0x6c, 0xd7, 0xb6, 0x9e, 0x67, 0x34, 0xf4, 0x34, 0x4a, 0x6a,
	0x3c, 0xa4, 0xfe, 0x69, 0x63, 0x13, 0x13, 0x8a, 0xc4, 0x34, 0xc1, 0xb6, 0x1e, 0xa8, 0x89, 0x5f,
	0xc8, 0x71, 0xac, 0x78, 0x01, 0x76, 0xd7, 0xbb, 0xbd, 0x4b, 0x48, 0x7c, 0x22, 0xdf, 0x40, 0x9f,
	0xc0, 0x8f, 0xbe, 0x8b, 0x2f, 0x60, 0x76, 0xef, 0x0a, 0x47, 0x0a, 0xa4, 0x7e, 0xf0, 0xdb, 0xec,
	0xfc, 0xf9, 0xed, 0xcc, 0x6f, 0x66, 0x67, 0xe1, 0x61, 0xdf, 0x66, 0x5e, 0x95, 0x79, 0x94, 0xd3,
	0xaa, 0x17, 0x10, 0xee, 0x8e, 0x71, 0x35, 0xac, 0x55, 0x6d, 0xc6, 0x1c, 0x7b, 0x34, 0xea, 0xd9,
	0xce, 0xd0, 0x94, 0x46, 0xb4, 0x2d, 0x1c, 0x23, 0xd9, 0x8c, 0x1d, 0xcd, 0xb0, 0xa6, 0xdf, 0x1e,
	0x50, 0x3a, 0x18, 0xe1, 0x08, 0xa1, 0x17, 0x7c, 0xae, 0xe2, 0x31, 0xe3, 0x93, 0xc8, 0x4f, 0xdf,
	0x4d, 0x80, 0x3b, 0x74, 0x3c, 0xa6, 0x44, 0x60, 0x47, 0x52, 0xe4, 0x62, 0xfc, 0x52, 0x60, 0xb3,
	0x43, 0x99, 0xeb, 0x34, 0x43, 0x4c, 0xb8, 0x85, 0xbf, 0x06, 0xd8, 0xe7, 0xa8, 0x04, 0xaa, 0xdb,
	0xd7, 0x94, 0xb2, 0x52, 0xc9, 0x5b, 0xaa, 0xdb, 0x47, 0x3b, 0x90, 0xf5, 0x69, 0xe0, 0x39, 0x58,
	0x53, 0xa5, 0x2e, 0x3e, 0x21, 0x04, 0x19, 0x3e, 0x61, 0x58, 0x4b, 0x4b, 0xad, 0x94, 0xd1, 0x2e,
	0x14, 0x7d, 0x86, 0x9d, 0x6e, 0x88, 0x3d, 0xdf, 0xa5, 0x44, 0xcb, 0x48, 0x5b, 0x41, 0xe8, 0x3e,
	0x44, 0x2a, 0xb4, 0x07, 0x9b, 0x7d, 0x9b, 0xdb, 0x5d, 0x87, 0x12, 0x8e, 0x09, 0xef, 0x4a, 0x8c,
	0x35, 0xe9, 0x77, 0x5d, 0x18, 0x1a, 0x91, 0xbe, 0x23, 0xe0, 0x10, 0x64, 0x84, 0x4a, 0xbb, 0x56,
	0x56, 0x2a, 0x45, 0x4b, 0xca, 0x68, 0x0b, 0xd6, 0xb8, 0xc8, 0x59, 0xcb, 0xca, 0x98, 0xe8, 0x60,
	0xfc, 0x56, 0xe0, 0xc6, 0xb1, 0x4b, 0xfa, 0x2e, 0x19, 0xcc, 0x15, 0x83, 0x20, 0x43, 0xec, 0x31,
	0x8e, 0xcb, 0x91, 0xf2, 0x14, 0x55, 0x4d, 0xa0, 0x76, 0x20, 0x37, 0xc6, 0xdc, 0x96, 0xfa, 0x74,
	0x39, 0x5d, 0x29, 0xec, 0x1f, 0x9a, 0x0b, 0x49, 0x37, 0x17, 0xdc, 0x62, 0xbe, 0x8d, 0x43, 0x9b,
	0x84, 0x7b, 0x13, 0x6b, 0x8a, 0xa4, 0x1f, 0xc1, 0xfa, 0x9c, 0x09, 0x6d, 0x40, 0x7a, 0x88, 0x27,
	0x71, 0x36, 0x42, 0x14, 0xe5, 0x84, 0xf6, 0x28, 0xb8, 0x20, 0x37, 0x3a, 0xbc, 0x54, 0x0f, 0x15,
	0xe3, 0x87, 0x0a, 0x5b, 0xf3, 0x97, 0xf9, 0x8c, 0x12, 0x1f, 0xa3, 0x3b, 0x00, 0x3e, 0xa7, 0x1e,
	0xee, 0x26, 0x2a, 0xcb, 0x4b, 0xcd, 0xa9, 0x28, 0xef, 0x15, 0x64, 0x7d, 0x6e, 0x73, 0xec, 0x6b,
	0xaa, 0x2c, 0xe4, 0x41, 0xb2, 0x90, 0xb8, 0xff, 0x61, 0xcd, 0x6c, 0x0b, 0x9f, 0xb6, 0x1d, 0xe2,
	0xb8, 0x08, 0x2b, 0x8e, 0x12, 0xfd, 0xe7, 0x54, 0x92, 0x90, 0xb7, 0x54, 0x4e, 0xa7, 0x74, 0x65,
	0x12, 0x74, 0x61, 0x28, 0x38, 0x94, 0x38, 0x81, 0xe7, 0x61, 0xe2, 0x4c, 0x64, 0xfb, 0x4a, 0xfb,
	0x8d, 0x2b, 0x31, 0x16, 0x15, 0x31, 0xa7, 0x6c, 0xcc, 0xa0, 0xac, 0x24, 0xae, 0x71, 0x00, 0x37,
	0x97, 0xf8, 0xa1, 0x12, 0x40, 0xbb, 0xf9, 0xee, 0x7d, 0xf3, 0xb4, 0x73, 0x52, 0x6f, 0x6d, 0xa4,
	0x50, 0x11, 0x72, 0xe7, 0x75, 0xab, 0xde, 0x6a, 0x35, 0x5b, 0x1b, 0x8a, 0xc1, 0xe0, 0x6e, 0xcb,
	0xf5, 0xb9, 0x1c, 0xee, 0x76, 0xd0, 0xf3, 0x1d, 0xcf, 0x65, 0xdc, 0xa5, 0xc4, 0x9f, 0x92, 0x78,
	0x0a, 0xeb, 0x7e, 0xd2, 0xa0, 0x29, 0x92, 0xac, 0xca, 0x92, 0x1a, 0x2e, 0x21, 0x59, 0xf3, 0xe1,
	0xc6, 0xcf, 0x8b, 0xb7, 0x94, 0x74, 0x9a, 0x0d, 0xab, 0x92, 0x18, 0x56, 0x64, 0x25, 0x86, 0x2d,
	0xea, 0xd1, 0x8b, 0xab, 0x5e, 0xfb, 0x7f, 0x46, 0xed, 0x00, 0x6e, 0x09, 0xba, 0x4e, 0x08, 0x0b,
	0x78, 0x4c, 0xf8, 0x8c, 0x29, 0x1d, 0x72, 0xbd, 0x58, 0x27, 0x49, 0xca, 0x5b, 0xd3, 0xf3, 0xfe,
	0x9f, 0x34, 0x14, 0xea, 0x8c, 0x35, 0xe2, 0x75, 0x85, 0x3e, 0x42, 0xee, 0x8c, 0x9c, 0x90, 0x90,
	0x0e, 0x31, 0xba, 0xb7, 0x78, 0xee, 0x22, 0x6b, 0x3c, 0x74, 0xfa, 0xfd, 0xd5, 0x4e, 0x51, 0x0a,
	0x46, 0x0a, 0xb9, 0xb0, 0xb3, 0xb8, 0xa1, 0x68, 0xc7, 0x8c, 0xb6, 0xa0, 0x79, 0xb1, 0x05, 0xcd,
	0xa6, 0xd8, 0x82, 0xfa, 0xf3, 0x25, 0x94, 0xae, 0x9e, 0x0b, 0x23, 0x85, 0x2c, 0x28, 0x9e, 0x91,
	0xd9, 0x5a, 0x44, 0x2b, 0x47, 0x22, 0xb9, 0x06, 0xf4, 0x25, 0xa9, 0x18, 0x29, 0xd4, 0x85, 0xcd,
	0x4b, 0x04, 0x2f, 0xcd, 0xfc, 0xc9, 0x8a, 0xcc, 0x17, 0xb6, 0xc8, 0x48, 0xa1, 0x21, 0x94, 0xce,
	0x48, 0xf2, 0xad, 0xa0, 0xbd, 0xab, 0xef, 0x2f, 0xfd, 0xd1, 0x3f, 0xbc, 0x5c, 0x23, 0x75, 0xfc,
	0x0d, 0xc0, 0xa5, 0x51, 0x48, 0x58, 0x3b, 0xde, 0x7e, 0x6d, 0x33, 0x2f, 0x31, 0x04, 0xe7, 0x02,
	0xc5, 0xff, 0xf4, 0x6c, 0xe0, 0xf2, 0x2f, 0x41, 0x4f, 0x34, 0xb5, 0x2a, 0xbf, 0xa2, 0x01, 0x7d,
	0xec, 0xf7, 0x87, 0xd5, 0x85, 0x7f, 0xde, 0x51, 0x2c, 0x7e, 0x57, 0xcb, 0x02, 0xcd, 0x4c, 0xc0,
	0x99, 0xf5, 0x80, 0xd3, 0x01, 0x26, 0xe6, 0x1b, 0x8f, 0x39, 0x66, 0x58, 0xeb, 0x65, 0x65, 0xf0,
	0xd3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0x4f, 0x4a, 0x8f, 0x3e, 0x07, 0x00, 0x00,
>>>>>>> upstream/master
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
<<<<<<< HEAD
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6
=======
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4
>>>>>>> upstream/master

// AppCallbackClient is the client API for AppCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppCallbackClient interface {
	// Invokes service method with InvokeRequest.
	OnInvoke(ctx context.Context, in *v1.InvokeRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error)
	// Lists all topics subscribed by this app.
	ListTopicSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTopicSubscriptionsResponse, error)
	// Subscribes events from Pubsub
	OnTopicEvent(ctx context.Context, in *TopicEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Lists all input bindings subscribed by this app.
	ListInputBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListInputBindingsResponse, error)
	// Listens events from the input bindings
	//
	// User application can save the states or send the events to the output
	// bindings optionally by returning BindingEventResponse.
	OnBindingEvent(ctx context.Context, in *BindingEventRequest, opts ...grpc.CallOption) (*BindingEventResponse, error)
}

type appCallbackClient struct {
<<<<<<< HEAD
	cc grpc.ClientConnInterface
}

func NewAppCallbackClient(cc grpc.ClientConnInterface) AppCallbackClient {
=======
	cc *grpc.ClientConn
}

func NewAppCallbackClient(cc *grpc.ClientConn) AppCallbackClient {
>>>>>>> upstream/master
	return &appCallbackClient{cc}
}

func (c *appCallbackClient) OnInvoke(ctx context.Context, in *v1.InvokeRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error) {
	out := new(v1.InvokeResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.AppCallback/OnInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) ListTopicSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTopicSubscriptionsResponse, error) {
	out := new(ListTopicSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.AppCallback/ListTopicSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) OnTopicEvent(ctx context.Context, in *TopicEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.AppCallback/OnTopicEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) ListInputBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListInputBindingsResponse, error) {
	out := new(ListInputBindingsResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.AppCallback/ListInputBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) OnBindingEvent(ctx context.Context, in *BindingEventRequest, opts ...grpc.CallOption) (*BindingEventResponse, error) {
	out := new(BindingEventResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.AppCallback/OnBindingEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppCallbackServer is the server API for AppCallback service.
type AppCallbackServer interface {
	// Invokes service method with InvokeRequest.
	OnInvoke(context.Context, *v1.InvokeRequest) (*v1.InvokeResponse, error)
	// Lists all topics subscribed by this app.
	ListTopicSubscriptions(context.Context, *empty.Empty) (*ListTopicSubscriptionsResponse, error)
	// Subscribes events from Pubsub
	OnTopicEvent(context.Context, *TopicEventRequest) (*empty.Empty, error)
	// Lists all input bindings subscribed by this app.
	ListInputBindings(context.Context, *empty.Empty) (*ListInputBindingsResponse, error)
	// Listens events from the input bindings
	//
	// User application can save the states or send the events to the output
	// bindings optionally by returning BindingEventResponse.
	OnBindingEvent(context.Context, *BindingEventRequest) (*BindingEventResponse, error)
}

// UnimplementedAppCallbackServer can be embedded to have forward compatible implementations.
type UnimplementedAppCallbackServer struct {
}

<<<<<<< HEAD
func (*UnimplementedAppCallbackServer) OnInvoke(context.Context, *v1.InvokeRequest) (*v1.InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnInvoke not implemented")
}
func (*UnimplementedAppCallbackServer) ListTopicSubscriptions(context.Context, *empty.Empty) (*ListTopicSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopicSubscriptions not implemented")
}
func (*UnimplementedAppCallbackServer) OnTopicEvent(context.Context, *TopicEventRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTopicEvent not implemented")
}
func (*UnimplementedAppCallbackServer) ListInputBindings(context.Context, *empty.Empty) (*ListInputBindingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInputBindings not implemented")
}
func (*UnimplementedAppCallbackServer) OnBindingEvent(context.Context, *BindingEventRequest) (*BindingEventResponse, error) {
=======
func (*UnimplementedAppCallbackServer) OnInvoke(ctx context.Context, req *v1.InvokeRequest) (*v1.InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnInvoke not implemented")
}
func (*UnimplementedAppCallbackServer) ListTopicSubscriptions(ctx context.Context, req *empty.Empty) (*ListTopicSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopicSubscriptions not implemented")
}
func (*UnimplementedAppCallbackServer) OnTopicEvent(ctx context.Context, req *TopicEventRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTopicEvent not implemented")
}
func (*UnimplementedAppCallbackServer) ListInputBindings(ctx context.Context, req *empty.Empty) (*ListInputBindingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInputBindings not implemented")
}
func (*UnimplementedAppCallbackServer) OnBindingEvent(ctx context.Context, req *BindingEventRequest) (*BindingEventResponse, error) {
>>>>>>> upstream/master
	return nil, status.Errorf(codes.Unimplemented, "method OnBindingEvent not implemented")
}

func RegisterAppCallbackServer(s *grpc.Server, srv AppCallbackServer) {
	s.RegisterService(&_AppCallback_serviceDesc, srv)
}

func _AppCallback_OnInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.AppCallback/OnInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnInvoke(ctx, req.(*v1.InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_ListTopicSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).ListTopicSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.AppCallback/ListTopicSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).ListTopicSubscriptions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_OnTopicEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnTopicEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.AppCallback/OnTopicEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnTopicEvent(ctx, req.(*TopicEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_ListInputBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).ListInputBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.AppCallback/ListInputBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).ListInputBindings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_OnBindingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnBindingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.AppCallback/OnBindingEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnBindingEvent(ctx, req.(*BindingEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppCallback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.AppCallback",
	HandlerType: (*AppCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnInvoke",
			Handler:    _AppCallback_OnInvoke_Handler,
		},
		{
			MethodName: "ListTopicSubscriptions",
			Handler:    _AppCallback_ListTopicSubscriptions_Handler,
		},
		{
			MethodName: "OnTopicEvent",
			Handler:    _AppCallback_OnTopicEvent_Handler,
		},
		{
			MethodName: "ListInputBindings",
			Handler:    _AppCallback_ListInputBindings_Handler,
		},
		{
			MethodName: "OnBindingEvent",
			Handler:    _AppCallback_OnBindingEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/appcallback.proto",
}
