// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daprclient.proto

package daprclient

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloudEventEnvelope struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SpecVersion          string   `protobuf:"bytes,4,opt,name=specVersion,proto3" json:"specVersion,omitempty"`
	DataContentType      string   `protobuf:"bytes,5,opt,name=dataContentType,proto3" json:"dataContentType,omitempty"`
	Topic                string   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 *any.Any `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudEventEnvelope) Reset()         { *m = CloudEventEnvelope{} }
func (m *CloudEventEnvelope) String() string { return proto.CompactTextString(m) }
func (*CloudEventEnvelope) ProtoMessage()    {}
func (*CloudEventEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{0}
}

func (m *CloudEventEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudEventEnvelope.Unmarshal(m, b)
}
func (m *CloudEventEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudEventEnvelope.Marshal(b, m, deterministic)
}
func (m *CloudEventEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudEventEnvelope.Merge(m, src)
}
func (m *CloudEventEnvelope) XXX_Size() int {
	return xxx_messageInfo_CloudEventEnvelope.Size(m)
}
func (m *CloudEventEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudEventEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_CloudEventEnvelope proto.InternalMessageInfo

func (m *CloudEventEnvelope) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloudEventEnvelope) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CloudEventEnvelope) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CloudEventEnvelope) GetSpecVersion() string {
	if m != nil {
		return m.SpecVersion
	}
	return ""
}

func (m *CloudEventEnvelope) GetDataContentType() string {
	if m != nil {
		return m.DataContentType
	}
	return ""
}

func (m *CloudEventEnvelope) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CloudEventEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type BindingEventEnvelope struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 *any.Any          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BindingEventEnvelope) Reset()         { *m = BindingEventEnvelope{} }
func (m *BindingEventEnvelope) String() string { return proto.CompactTextString(m) }
func (*BindingEventEnvelope) ProtoMessage()    {}
func (*BindingEventEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{1}
}

func (m *BindingEventEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingEventEnvelope.Unmarshal(m, b)
}
func (m *BindingEventEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingEventEnvelope.Marshal(b, m, deterministic)
}
func (m *BindingEventEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingEventEnvelope.Merge(m, src)
}
func (m *BindingEventEnvelope) XXX_Size() int {
	return xxx_messageInfo_BindingEventEnvelope.Size(m)
}
func (m *BindingEventEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingEventEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_BindingEventEnvelope proto.InternalMessageInfo

func (m *BindingEventEnvelope) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BindingEventEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BindingEventEnvelope) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type BindingResponseEnvelope struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	State                []*State `protobuf:"bytes,3,rep,name=state,proto3" json:"state,omitempty"`
	Concurrency          string   `protobuf:"bytes,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindingResponseEnvelope) Reset()         { *m = BindingResponseEnvelope{} }
func (m *BindingResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*BindingResponseEnvelope) ProtoMessage()    {}
func (*BindingResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{2}
}

func (m *BindingResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingResponseEnvelope.Unmarshal(m, b)
}
func (m *BindingResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *BindingResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingResponseEnvelope.Merge(m, src)
}
func (m *BindingResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_BindingResponseEnvelope.Size(m)
}
func (m *BindingResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_BindingResponseEnvelope proto.InternalMessageInfo

func (m *BindingResponseEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BindingResponseEnvelope) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *BindingResponseEnvelope) GetState() []*State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *BindingResponseEnvelope) GetConcurrency() string {
	if m != nil {
		return m.Concurrency
	}
	return ""
}

type InvokeEnvelope struct {
	Method               string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Data                 *any.Any          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeEnvelope) Reset()         { *m = InvokeEnvelope{} }
func (m *InvokeEnvelope) String() string { return proto.CompactTextString(m) }
func (*InvokeEnvelope) ProtoMessage()    {}
func (*InvokeEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{3}
}

func (m *InvokeEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeEnvelope.Unmarshal(m, b)
}
func (m *InvokeEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeEnvelope.Marshal(b, m, deterministic)
}
func (m *InvokeEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeEnvelope.Merge(m, src)
}
func (m *InvokeEnvelope) XXX_Size() int {
	return xxx_messageInfo_InvokeEnvelope.Size(m)
}
func (m *InvokeEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeEnvelope proto.InternalMessageInfo

func (m *InvokeEnvelope) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InvokeEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvokeEnvelope) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetTopicSubscriptionsEnvelope struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicSubscriptionsEnvelope) Reset()         { *m = GetTopicSubscriptionsEnvelope{} }
func (m *GetTopicSubscriptionsEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTopicSubscriptionsEnvelope) ProtoMessage()    {}
func (*GetTopicSubscriptionsEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{4}
}

func (m *GetTopicSubscriptionsEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicSubscriptionsEnvelope.Unmarshal(m, b)
}
func (m *GetTopicSubscriptionsEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicSubscriptionsEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTopicSubscriptionsEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicSubscriptionsEnvelope.Merge(m, src)
}
func (m *GetTopicSubscriptionsEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTopicSubscriptionsEnvelope.Size(m)
}
func (m *GetTopicSubscriptionsEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicSubscriptionsEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicSubscriptionsEnvelope proto.InternalMessageInfo

func (m *GetTopicSubscriptionsEnvelope) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type GetBindingsSubscriptionsEnvelope struct {
	Bindings             []string `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBindingsSubscriptionsEnvelope) Reset()         { *m = GetBindingsSubscriptionsEnvelope{} }
func (m *GetBindingsSubscriptionsEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetBindingsSubscriptionsEnvelope) ProtoMessage()    {}
func (*GetBindingsSubscriptionsEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{5}
}

func (m *GetBindingsSubscriptionsEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBindingsSubscriptionsEnvelope.Unmarshal(m, b)
}
func (m *GetBindingsSubscriptionsEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBindingsSubscriptionsEnvelope.Marshal(b, m, deterministic)
}
func (m *GetBindingsSubscriptionsEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBindingsSubscriptionsEnvelope.Merge(m, src)
}
func (m *GetBindingsSubscriptionsEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetBindingsSubscriptionsEnvelope.Size(m)
}
func (m *GetBindingsSubscriptionsEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBindingsSubscriptionsEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetBindingsSubscriptionsEnvelope proto.InternalMessageInfo

func (m *GetBindingsSubscriptionsEnvelope) GetBindings() []string {
	if m != nil {
		return m.Bindings
	}
	return nil
}

type State struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Etag                 string            `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options              *StateOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{6}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *State) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *State) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *State) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *State) GetOptions() *StateOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type StateOptions struct {
	Concurrency          string       `protobuf:"bytes,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Consistency          string       `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	RetryPolicy          *RetryPolicy `protobuf:"bytes,3,opt,name=retryPolicy,proto3" json:"retryPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StateOptions) Reset()         { *m = StateOptions{} }
func (m *StateOptions) String() string { return proto.CompactTextString(m) }
func (*StateOptions) ProtoMessage()    {}
func (*StateOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{7}
}

func (m *StateOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateOptions.Unmarshal(m, b)
}
func (m *StateOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateOptions.Marshal(b, m, deterministic)
}
func (m *StateOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateOptions.Merge(m, src)
}
func (m *StateOptions) XXX_Size() int {
	return xxx_messageInfo_StateOptions.Size(m)
}
func (m *StateOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StateOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StateOptions proto.InternalMessageInfo

func (m *StateOptions) GetConcurrency() string {
	if m != nil {
		return m.Concurrency
	}
	return ""
}

func (m *StateOptions) GetConsistency() string {
	if m != nil {
		return m.Consistency
	}
	return ""
}

func (m *StateOptions) GetRetryPolicy() *RetryPolicy {
	if m != nil {
		return m.RetryPolicy
	}
	return nil
}

type RetryPolicy struct {
	Threshold            int32              `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Pattern              string             `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Interval             *duration.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RetryPolicy) Reset()         { *m = RetryPolicy{} }
func (m *RetryPolicy) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy) ProtoMessage()    {}
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d5244029ccc8f, []int{8}
}

func (m *RetryPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy.Unmarshal(m, b)
}
func (m *RetryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy.Marshal(b, m, deterministic)
}
func (m *RetryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy.Merge(m, src)
}
func (m *RetryPolicy) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy.Size(m)
}
func (m *RetryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy proto.InternalMessageInfo

func (m *RetryPolicy) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *RetryPolicy) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *RetryPolicy) GetInterval() *duration.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudEventEnvelope)(nil), "daprclient.CloudEventEnvelope")
	proto.RegisterType((*BindingEventEnvelope)(nil), "daprclient.BindingEventEnvelope")
	proto.RegisterMapType((map[string]string)(nil), "daprclient.BindingEventEnvelope.MetadataEntry")
	proto.RegisterType((*BindingResponseEnvelope)(nil), "daprclient.BindingResponseEnvelope")
	proto.RegisterType((*InvokeEnvelope)(nil), "daprclient.InvokeEnvelope")
	proto.RegisterMapType((map[string]string)(nil), "daprclient.InvokeEnvelope.MetadataEntry")
	proto.RegisterType((*GetTopicSubscriptionsEnvelope)(nil), "daprclient.GetTopicSubscriptionsEnvelope")
	proto.RegisterType((*GetBindingsSubscriptionsEnvelope)(nil), "daprclient.GetBindingsSubscriptionsEnvelope")
	proto.RegisterType((*State)(nil), "daprclient.State")
	proto.RegisterMapType((map[string]string)(nil), "daprclient.State.MetadataEntry")
	proto.RegisterType((*StateOptions)(nil), "daprclient.StateOptions")
	proto.RegisterType((*RetryPolicy)(nil), "daprclient.RetryPolicy")
}

func init() { proto.RegisterFile("daprclient.proto", fileDescriptor_127d5244029ccc8f) }

var fileDescriptor_127d5244029ccc8f = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0xdb, 0x4a,
	0x10, 0xb6, 0xe4, 0xdf, 0x8c, 0x73, 0x7c, 0x72, 0x86, 0x9c, 0x44, 0x51, 0xce, 0x49, 0x8d, 0x7a,
	0x51, 0xb7, 0x14, 0x07, 0x5c, 0x4a, 0x7f, 0x02, 0x81, 0x26, 0x31, 0x69, 0x0b, 0xc5, 0x41, 0x09,
	0x85, 0x42, 0x6f, 0x64, 0x79, 0xeb, 0x88, 0xc8, 0xbb, 0x62, 0xb5, 0x36, 0x08, 0x7a, 0xdf, 0xab,
	0xbe, 0x42, 0x5f, 0xa2, 0xcf, 0xd2, 0xbb, 0xf6, 0x5d, 0x8a, 0x56, 0x2b, 0x7b, 0xe3, 0x9f, 0x84,
	0x52, 0x7a, 0xa7, 0x9d, 0xef, 0x9b, 0x9d, 0xf9, 0xe6, 0x67, 0x05, 0x1b, 0x03, 0x2f, 0xe2, 0x7e,
	0x18, 0x10, 0x2a, 0xda, 0x11, 0x67, 0x82, 0x21, 0xcc, 0x2c, 0xf6, 0xce, 0x90, 0xb1, 0x61, 0x48,
	0xf6, 0x25, 0xd2, 0x1f, 0x7f, 0xd8, 0xf7, 0x68, 0x92, 0xd1, 0xec, 0xdd, 0x79, 0x88, 0x8c, 0x22,
	0x91, 0x83, 0x7b, 0xf3, 0xe0, 0x60, 0xcc, 0x3d, 0x11, 0x30, 0x9a, 0xe1, 0xce, 0x77, 0x03, 0xf0,
	0x38, 0x64, 0xe3, 0x41, 0x77, 0x42, 0xa8, 0xe8, 0xd2, 0x09, 0x09, 0x59, 0x44, 0xb0, 0x01, 0x66,
	0x30, 0xb0, 0x8c, 0xa6, 0xd1, 0x5a, 0x73, 0xcd, 0x60, 0x80, 0x5b, 0x50, 0x89, 0xd9, 0x98, 0xfb,
	0xc4, 0x32, 0xa5, 0x4d, 0x9d, 0x10, 0xa1, 0x24, 0x92, 0x88, 0x58, 0x45, 0x69, 0x95, 0xdf, 0xd8,
	0x84, 0x7a, 0x1c, 0x11, 0xff, 0x2d, 0xe1, 0x71, 0xc0, 0xa8, 0x55, 0x92, 0x90, 0x6e, 0xc2, 0x16,
	0xfc, 0x3d, 0xf0, 0x84, 0x77, 0xcc, 0xa8, 0x20, 0x54, 0x5c, 0xa4, 0x17, 0x94, 0x25, 0x6b, 0xde,
	0x8c, 0x9b, 0x50, 0x16, 0x2c, 0x0a, 0x7c, 0xab, 0x22, 0xf1, 0xec, 0x80, 0x2d, 0x28, 0xa5, 0x44,
	0xab, 0xda, 0x34, 0x5a, 0xf5, 0xce, 0x66, 0x3b, 0xd3, 0xd8, 0xce, 0x35, 0xb6, 0x5f, 0xd0, 0xc4,
	0x95, 0x0c, 0xe7, 0x87, 0x01, 0x9b, 0x47, 0x01, 0x1d, 0x04, 0x74, 0x78, 0x5d, 0x20, 0x42, 0x89,
	0x7a, 0x23, 0xa2, 0x24, 0xca, 0xef, 0xe9, 0xb5, 0xe6, 0x6d, 0xd7, 0xe2, 0x6b, 0xa8, 0x8d, 0x88,
	0xf0, 0x24, 0xbb, 0xd8, 0x2c, 0xb6, 0xea, 0x9d, 0x76, 0x5b, 0x6b, 0xdf, 0xb2, 0x88, 0xed, 0x37,
	0xca, 0xa1, 0x4b, 0x05, 0x4f, 0xdc, 0xa9, 0xbf, 0x7d, 0x00, 0x7f, 0x5d, 0x83, 0x70, 0x03, 0x8a,
	0x57, 0x24, 0x51, 0x99, 0xa5, 0x9f, 0x69, 0x15, 0x26, 0x5e, 0x38, 0xce, 0x8b, 0x9f, 0x1d, 0x9e,
	0x9b, 0x4f, 0x0d, 0xe7, 0x8b, 0x01, 0xdb, 0x2a, 0x9a, 0x4b, 0xe2, 0x88, 0xd1, 0x98, 0x4c, 0x25,
	0xe6, 0x72, 0x8c, 0x5b, 0xe5, 0x34, 0xc0, 0x14, 0xcc, 0x32, 0x9b, 0xc5, 0xb4, 0xdb, 0x82, 0xe1,
	0x3d, 0x28, 0xc7, 0xc2, 0x13, 0x44, 0x69, 0xfb, 0x47, 0xd7, 0x76, 0x9e, 0x02, 0x6e, 0x86, 0xa7,
	0xad, 0xf6, 0x19, 0xf5, 0xc7, 0x9c, 0x13, 0xea, 0x27, 0x79, 0xab, 0x35, 0x93, 0xf3, 0xcd, 0x80,
	0xc6, 0x2b, 0x3a, 0x61, 0x57, 0xb3, 0xbc, 0xb6, 0xa0, 0x32, 0x22, 0xe2, 0x92, 0xe5, 0xf3, 0xa5,
	0x4e, 0xbf, 0x50, 0xfe, 0x93, 0x85, 0xf2, 0xb7, 0xf4, 0x14, 0xaf, 0xc7, 0xfb, 0x33, 0x85, 0x7f,
	0x02, 0xff, 0x9f, 0x12, 0x71, 0x91, 0x8e, 0xe3, 0xf9, 0xb8, 0x1f, 0xfb, 0x3c, 0x88, 0xd2, 0xad,
	0x8a, 0x75, 0x95, 0x72, 0x58, 0x63, 0xcb, 0x90, 0x75, 0x55, 0x27, 0xe7, 0x10, 0x9a, 0xa7, 0x44,
	0xa8, 0x9e, 0xc5, 0xcb, 0x7d, 0x6d, 0xa8, 0xf5, 0x15, 0x41, 0x79, 0x4f, 0xcf, 0xce, 0x27, 0x13,
	0xca, 0xb2, 0x07, 0x4b, 0xd2, 0x7d, 0xa0, 0xa7, 0xbb, 0xaa, 0x84, 0x19, 0x25, 0x5d, 0x00, 0x22,
	0xbc, 0x61, 0xbe, 0xb9, 0xe9, 0x37, 0x1e, 0x68, 0x75, 0x2d, 0xc9, 0xba, 0xde, 0x59, 0x68, 0xfd,
	0xaa, 0x72, 0x62, 0x07, 0xaa, 0x2c, 0xd3, 0x21, 0x97, 0xb9, 0xde, 0xb1, 0x16, 0x7c, 0x7b, 0x19,
	0xee, 0xe6, 0xc4, 0xdf, 0x6b, 0xc1, 0x67, 0x03, 0xd6, 0xf5, 0x6b, 0xe7, 0xa7, 0xd1, 0x58, 0x98,
	0x46, 0xc5, 0x88, 0x83, 0x58, 0x48, 0x86, 0x39, 0x65, 0xe4, 0x26, 0x7c, 0x06, 0x75, 0x4e, 0x04,
	0x4f, 0xce, 0x58, 0x18, 0xf8, 0x89, 0xac, 0x4e, 0xbd, 0xb3, 0xad, 0x2b, 0x71, 0x67, 0xb0, 0xab,
	0x73, 0x9d, 0x8f, 0x50, 0xd7, 0x30, 0xfc, 0x0f, 0xd6, 0xc4, 0x25, 0x27, 0xf1, 0x25, 0x0b, 0xb3,
	0x49, 0x2f, 0xbb, 0x33, 0x03, 0x5a, 0x50, 0x8d, 0x3c, 0x21, 0x08, 0xa7, 0x2a, 0x8b, 0xfc, 0x88,
	0x8f, 0xa1, 0x16, 0x50, 0x41, 0xf8, 0xc4, 0x0b, 0x55, 0xf8, 0x9d, 0x85, 0x3e, 0x9e, 0xa8, 0x47,
	0xdc, 0x9d, 0x52, 0x3b, 0x5f, 0x8b, 0x00, 0x27, 0x5e, 0xc4, 0x8f, 0x65, 0x96, 0x78, 0x08, 0xb5,
	0x1e, 0xcd, 0x16, 0x01, 0xed, 0xd5, 0xcb, 0x61, 0x2f, 0x9d, 0x11, 0xa7, 0x80, 0xef, 0xe1, 0xdf,
	0xa5, 0xf3, 0x8d, 0x5b, 0x0b, 0x0e, 0xdd, 0xf4, 0x77, 0x63, 0xdf, 0xd7, 0x83, 0xdc, 0xb8, 0x1a,
	0x4e, 0x01, 0xfb, 0x60, 0xad, 0x5a, 0x82, 0x95, 0x01, 0x1e, 0xce, 0x05, 0xb8, 0x71, 0x85, 0x9c,
	0x02, 0xbe, 0x83, 0x46, 0x8f, 0xea, 0x2f, 0x31, 0x36, 0x6f, 0x7b, 0xa3, 0xed, 0xbb, 0x4b, 0x18,
	0xf3, 0xef, 0xaa, 0x53, 0xc0, 0x97, 0xb0, 0xde, 0xa3, 0x52, 0x60, 0x76, 0xf1, 0x9e, 0xee, 0xb6,
	0xf8, 0x37, 0xb5, 0x57, 0x48, 0x72, 0x0a, 0x47, 0xbb, 0x50, 0x0d, 0x98, 0xf4, 0x3e, 0xda, 0x98,
	0x75, 0xef, 0x2c, 0xa5, 0xc5, 0xfd, 0x8a, 0xa4, 0x3f, 0xfa, 0x19, 0x00, 0x00, 0xff, 0xff, 0x30,
	0x41, 0xfe, 0xa9, 0x1a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaprClientClient is the client API for DaprClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaprClientClient interface {
	OnInvoke(ctx context.Context, in *InvokeEnvelope, opts ...grpc.CallOption) (*any.Any, error)
	GetTopicSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTopicSubscriptionsEnvelope, error)
	GetBindingsSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBindingsSubscriptionsEnvelope, error)
	OnBindingEvent(ctx context.Context, in *BindingEventEnvelope, opts ...grpc.CallOption) (*BindingResponseEnvelope, error)
	OnTopicEvent(ctx context.Context, in *CloudEventEnvelope, opts ...grpc.CallOption) (*empty.Empty, error)
}

type daprClientClient struct {
	cc *grpc.ClientConn
}

func NewDaprClientClient(cc *grpc.ClientConn) DaprClientClient {
	return &daprClientClient{cc}
}

func (c *daprClientClient) OnInvoke(ctx context.Context, in *InvokeEnvelope, opts ...grpc.CallOption) (*any.Any, error) {
	out := new(any.Any)
	err := c.cc.Invoke(ctx, "/daprclient.DaprClient/OnInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClientClient) GetTopicSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTopicSubscriptionsEnvelope, error) {
	out := new(GetTopicSubscriptionsEnvelope)
	err := c.cc.Invoke(ctx, "/daprclient.DaprClient/GetTopicSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClientClient) GetBindingsSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBindingsSubscriptionsEnvelope, error) {
	out := new(GetBindingsSubscriptionsEnvelope)
	err := c.cc.Invoke(ctx, "/daprclient.DaprClient/GetBindingsSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClientClient) OnBindingEvent(ctx context.Context, in *BindingEventEnvelope, opts ...grpc.CallOption) (*BindingResponseEnvelope, error) {
	out := new(BindingResponseEnvelope)
	err := c.cc.Invoke(ctx, "/daprclient.DaprClient/OnBindingEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClientClient) OnTopicEvent(ctx context.Context, in *CloudEventEnvelope, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/daprclient.DaprClient/OnTopicEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaprClientServer is the server API for DaprClient service.
type DaprClientServer interface {
	OnInvoke(context.Context, *InvokeEnvelope) (*any.Any, error)
	GetTopicSubscriptions(context.Context, *empty.Empty) (*GetTopicSubscriptionsEnvelope, error)
	GetBindingsSubscriptions(context.Context, *empty.Empty) (*GetBindingsSubscriptionsEnvelope, error)
	OnBindingEvent(context.Context, *BindingEventEnvelope) (*BindingResponseEnvelope, error)
	OnTopicEvent(context.Context, *CloudEventEnvelope) (*empty.Empty, error)
}

func RegisterDaprClientServer(s *grpc.Server, srv DaprClientServer) {
	s.RegisterService(&_DaprClient_serviceDesc, srv)
}

func _DaprClient_OnInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprClientServer).OnInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprclient.DaprClient/OnInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprClientServer).OnInvoke(ctx, req.(*InvokeEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprClient_GetTopicSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprClientServer).GetTopicSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprclient.DaprClient/GetTopicSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprClientServer).GetTopicSubscriptions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprClient_GetBindingsSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprClientServer).GetBindingsSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprclient.DaprClient/GetBindingsSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprClientServer).GetBindingsSubscriptions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprClient_OnBindingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingEventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprClientServer).OnBindingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprclient.DaprClient/OnBindingEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprClientServer).OnBindingEvent(ctx, req.(*BindingEventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprClient_OnTopicEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudEventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprClientServer).OnTopicEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprclient.DaprClient/OnTopicEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprClientServer).OnTopicEvent(ctx, req.(*CloudEventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaprClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daprclient.DaprClient",
	HandlerType: (*DaprClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnInvoke",
			Handler:    _DaprClient_OnInvoke_Handler,
		},
		{
			MethodName: "GetTopicSubscriptions",
			Handler:    _DaprClient_GetTopicSubscriptions_Handler,
		},
		{
			MethodName: "GetBindingsSubscriptions",
			Handler:    _DaprClient_GetBindingsSubscriptions_Handler,
		},
		{
			MethodName: "OnBindingEvent",
			Handler:    _DaprClient_OnBindingEvent_Handler,
		},
		{
			MethodName: "OnTopicEvent",
			Handler:    _DaprClient_OnTopicEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daprclient.proto",
}
