version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    default_reviewers:
      - "mchmarny"
      - "yaron2"
      - "youngbupark"
      - "mukundansundar"
