# -*- mode: Python -*-

# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.


compile_cmd = 'CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o build/subscriber ./'

local_resource(
  'subscriber-go-compile',
  compile_cmd,
  deps=[ ])

docker_build(
  'seahope/saga-subscriber-go-image',
  '.',
  dockerfile='deployments/Dockerfile',
  only=[
    './build',
  ])
allow_k8s_contexts('default')
k8s_yaml('deployments/test_service_sub.yaml')
k8s_yaml('deployments/test_client_sub.yaml')
k8s_yaml('deployments/test_client2_sub.yaml')
k8s_yaml('deployments/kubernetes.yaml')
k8s_yaml('deployments/kubernetes1.yaml')
k8s_yaml('deployments/kubernetes2.yaml')


