apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wf-store
  namespace: default
  labels:
    app: payment-app
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: payment-app-redis:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
