all:
	dapr run \
                --app-id dapr-poller \
                --app-port 8080 \
                --app-protocol http \
                --resources-path ../../../components \
                go run app.go

