test:
	dapr run \
                --app-id dapr-test \
                --resources-path ../../../components \
                --app-port 6006 \
                go test service_test.go service.go interface.go
