# -*- mode: Python -*-

# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.


compile_cmd = 'CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o build/server_test ./'

local_resource(
  'server-test-go-compile',
  compile_cmd,
  deps=[ './server-test.go', './service.go', './interface.go'])

docker_build(
  'seahope/saga-server-test-go-image',
  '.',
  dockerfile='deployments/Dockerfile',
  only=[
    './build',

  ])
allow_k8s_contexts('default')
k8s_yaml('deployments/kubernetes.yaml')

