name: Test Dapr-Bot

on:
  push:
    paths: # Explicitly declare which paths
      - ".github/workflows/dapr-bot.yml"
      - ".github/workflows/dapr-bot/*"
  pull_request:
    branches:
      - main
    paths: # Explicitly declare which paths
      - ".github/workflows/dapr-bot.yml"
      - ".github/workflows/dapr-bot/*"

jobs:
  build:
    name: Test on ${{ matrix.gover }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gover:
          - "1.21"
    env:
      GOVER: ${{ matrix.gover }}
      GOLANGCILINT_VER: v1.54.2

    steps:
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVER }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Tidy
        working-directory: ./.github/workflows/dapr-bot
        run: make tidy

      - name: Test
        working-directory: ./.github/workflows/dapr-bot
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCILINT_VER }}
          working-directory: ./.github/workflows/dapr-bot
          skip-cache: true
          args: --timeout=10m0s --config ../../../.golangci.yml
