name: validate-examples

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:
  repository_dispatch:
    types: [validate-examples]
  merge_group:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      CHECKOUT_REPO: ${{ github.repository }}
      CHECKOUT_REF: ${{ github.ref }}
    outputs:
      CHECKOUT_REPO: ${{ steps.outputs.outputs.CHECKOUT_REPO }}
      CHECKOUT_REF: ${{ steps.outputs.outputs.CHECKOUT_REF }}
    steps:
      - name: Parse repository_dispatch payload
        if: github.event_name == 'repository_dispatch'
        run: |
          if [ ${{ github.event.client_payload.command }} = "ok-to-test" ]; then
            echo "CHECKOUT_REPO=${{ github.event.client_payload.pull_head_repo }}" >> $GITHUB_ENV
            echo "CHECKOUT_REF=${{ github.event.client_payload.pull_head_ref }}" >> $GITHUB_ENV
          fi

      - name: Check out code onto GOPATH
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CHECKOUT_REPO }}
          ref: ${{ env.CHECKOUT_REF }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run go mod tidy check diff
        run: make modtidy check-diff

      - name: Outputs
        id: outputs
        run: |
          echo "CHECKOUT_REPO=$CHECKOUT_REPO" >> "$GITHUB_OUTPUT"
          echo "CHECKOUT_REF=$CHECKOUT_REF" >> "$GITHUB_OUTPUT"

  validate-example:
    needs: setup
    runs-on: ubuntu-latest
    env:
      PYTHON_VER: 3.12
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      CHECKOUT_REPO: ${{ needs.setup.outputs.CHECKOUT_REPO }}
      CHECKOUT_REF: ${{ needs.setup.outputs.CHECKOUT_REF }}

    strategy:
      fail-fast: false
      matrix:
        examples:
          [
            "actor",
            "configuration",
            "conversation-alpha1",
            "conversation-alpha2",
            "crypto",
            "jobs",
            "grpc-service",
            "hello-world",
            "pubsub",
            "streamsub",
            "service",
            "socket",
            "workflow",
            "workflow-parallel",
            "workflow-taskexecutionid"
          ]
    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CHECKOUT_REPO }}
          ref: ${{ env.CHECKOUT_REF }}

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Set up Dapr CLI
        uses: dapr/.github/.github/actions/setup-dapr-cli@main

      - name: Initialize Dapr runtime
        uses: dapr/.github/.github/actions/setup-dapr-runtime@main

      - name: Print scheduler logs
        run: |
          docker logs dapr_scheduler

      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VER }}

      - name: Install Mechanical Markdown
        run: |
          python -m pip install --upgrade pip
          pip install mechanical-markdown

      - name: Check Example
        run: |
          cd examples
          ./validate.sh ${{ matrix.examples }}
