apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-client2
  labels:
    app: mock-client2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-client2
  template:
    metadata:
      annotations:
        dapr.io/app-id: mock-client2
        dapr.io/enabled: "true"
        dapr.io/app-port: "6009"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "error"
      creationTimestamp: null
      labels:
        app: mock-client2
    spec:
      containers:
      - name: mock-client2
        image: DOCKER_ID/mock-client2-go-image
        env:
        - name: APP_ID
          value: server-test
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "6009"
        - name: DAPR_METRICS_PORT
          value: "55215"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-url
              key: postgres-url
