//
//Copyright 2021 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dapr/proto/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of HTTP 1.1 Methods
// RFC 7231: https://tools.ietf.org/html/rfc7231#page-24
// RFC 5789: https://datatracker.ietf.org/doc/html/rfc5789
type HTTPExtension_Verb int32

const (
	HTTPExtension_NONE    HTTPExtension_Verb = 0
	HTTPExtension_GET     HTTPExtension_Verb = 1
	HTTPExtension_HEAD    HTTPExtension_Verb = 2
	HTTPExtension_POST    HTTPExtension_Verb = 3
	HTTPExtension_PUT     HTTPExtension_Verb = 4
	HTTPExtension_DELETE  HTTPExtension_Verb = 5
	HTTPExtension_CONNECT HTTPExtension_Verb = 6
	HTTPExtension_OPTIONS HTTPExtension_Verb = 7
	HTTPExtension_TRACE   HTTPExtension_Verb = 8
	HTTPExtension_PATCH   HTTPExtension_Verb = 9
)

// Enum value maps for HTTPExtension_Verb.
var (
	HTTPExtension_Verb_name = map[int32]string{
		0: "NONE",
		1: "GET",
		2: "HEAD",
		3: "POST",
		4: "PUT",
		5: "DELETE",
		6: "CONNECT",
		7: "OPTIONS",
		8: "TRACE",
		9: "PATCH",
	}
	HTTPExtension_Verb_value = map[string]int32{
		"NONE":    0,
		"GET":     1,
		"HEAD":    2,
		"POST":    3,
		"PUT":     4,
		"DELETE":  5,
		"CONNECT": 6,
		"OPTIONS": 7,
		"TRACE":   8,
		"PATCH":   9,
	}
)

func (x HTTPExtension_Verb) Enum() *HTTPExtension_Verb {
	p := new(HTTPExtension_Verb)
	*p = x
	return p
}

func (x HTTPExtension_Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTPExtension_Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (HTTPExtension_Verb) Type() protoreflect.EnumType {
	return &file_dapr_proto_common_v1_common_proto_enumTypes[0]
}

func (x HTTPExtension_Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTTPExtension_Verb.Descriptor instead.
func (HTTPExtension_Verb) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{0, 0}
}

// Enum describing the supported concurrency for state.
type StateOptions_StateConcurrency int32

const (
	StateOptions_CONCURRENCY_UNSPECIFIED StateOptions_StateConcurrency = 0
	StateOptions_CONCURRENCY_FIRST_WRITE StateOptions_StateConcurrency = 1
	StateOptions_CONCURRENCY_LAST_WRITE  StateOptions_StateConcurrency = 2
)

// Enum value maps for StateOptions_StateConcurrency.
var (
	StateOptions_StateConcurrency_name = map[int32]string{
		0: "CONCURRENCY_UNSPECIFIED",
		1: "CONCURRENCY_FIRST_WRITE",
		2: "CONCURRENCY_LAST_WRITE",
	}
	StateOptions_StateConcurrency_value = map[string]int32{
		"CONCURRENCY_UNSPECIFIED": 0,
		"CONCURRENCY_FIRST_WRITE": 1,
		"CONCURRENCY_LAST_WRITE":  2,
	}
)

func (x StateOptions_StateConcurrency) Enum() *StateOptions_StateConcurrency {
	p := new(StateOptions_StateConcurrency)
	*p = x
	return p
}

func (x StateOptions_StateConcurrency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateOptions_StateConcurrency) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (StateOptions_StateConcurrency) Type() protoreflect.EnumType {
	return &file_dapr_proto_common_v1_common_proto_enumTypes[1]
}

func (x StateOptions_StateConcurrency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateOptions_StateConcurrency.Descriptor instead.
func (StateOptions_StateConcurrency) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{6, 0}
}

// Enum describing the supported consistency for state.
type StateOptions_StateConsistency int32

const (
	StateOptions_CONSISTENCY_UNSPECIFIED StateOptions_StateConsistency = 0
	StateOptions_CONSISTENCY_EVENTUAL    StateOptions_StateConsistency = 1
	StateOptions_CONSISTENCY_STRONG      StateOptions_StateConsistency = 2
)

// Enum value maps for StateOptions_StateConsistency.
var (
	StateOptions_StateConsistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_EVENTUAL",
		2: "CONSISTENCY_STRONG",
	}
	StateOptions_StateConsistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED": 0,
		"CONSISTENCY_EVENTUAL":    1,
		"CONSISTENCY_STRONG":      2,
	}
)

func (x StateOptions_StateConsistency) Enum() *StateOptions_StateConsistency {
	p := new(StateOptions_StateConsistency)
	*p = x
	return p
}

func (x StateOptions_StateConsistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateOptions_StateConsistency) Descriptor() protoreflect.EnumDescriptor {
	return file_dapr_proto_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (StateOptions_StateConsistency) Type() protoreflect.EnumType {
	return &file_dapr_proto_common_v1_common_proto_enumTypes[2]
}

func (x StateOptions_StateConsistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateOptions_StateConsistency.Descriptor instead.
func (StateOptions_StateConsistency) EnumDescriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{6, 1}
}

// HTTPExtension includes HTTP verb and querystring
// when Dapr runtime delivers HTTP content.
//
// For example, when callers calls http invoke api
// `POST http://localhost:3500/v1.0/invoke/<app_id>/method/<method>?query1=value1&query2=value2`
//
// Dapr runtime will parse POST as a verb and extract querystring to quersytring map.
type HTTPExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. HTTP verb.
	Verb HTTPExtension_Verb `protobuf:"varint,1,opt,name=verb,proto3,enum=dapr.proto.common.v1.HTTPExtension_Verb" json:"verb,omitempty"`
	// Optional. querystring represents an encoded HTTP url query string in the following format: name=value&name2=value2
	Querystring   string `protobuf:"bytes,2,opt,name=querystring,proto3" json:"querystring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPExtension) Reset() {
	*x = HTTPExtension{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPExtension) ProtoMessage() {}

func (x *HTTPExtension) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPExtension.ProtoReflect.Descriptor instead.
func (*HTTPExtension) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPExtension) GetVerb() HTTPExtension_Verb {
	if x != nil {
		return x.Verb
	}
	return HTTPExtension_NONE
}

func (x *HTTPExtension) GetQuerystring() string {
	if x != nil {
		return x.Querystring
	}
	return ""
}

// InvokeRequest is the message to invoke a method with the data.
// This message is used in InvokeService of Dapr gRPC Service and OnInvoke
// of AppCallback gRPC service.
type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. method is a method name which will be invoked by caller.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Required in unary RPCs. Bytes value or Protobuf message which caller sent.
	// Dapr treats Any.value as bytes type if Any.type_url is unset.
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The type of data content.
	//
	// This field is required if data delivers http request body
	// Otherwise, this is optional.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// HTTP specific fields if request conveys http-compatible request.
	//
	// This field is required for http-compatible request. Otherwise,
	// this field is optional.
	HttpExtension *HTTPExtension `protobuf:"bytes,4,opt,name=http_extension,json=httpExtension,proto3" json:"http_extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InvokeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InvokeRequest) GetHttpExtension() *HTTPExtension {
	if x != nil {
		return x.HttpExtension
	}
	return nil
}

// InvokeResponse is the response message including data and its content type
// from app callback.
// This message is used in InvokeService of Dapr gRPC Service and OnInvoke
// of AppCallback gRPC service.
type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required in unary RPCs. The content body of InvokeService response.
	Data *anypb.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Required. The type of data content.
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InvokeResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Chunk of data sent in a streaming request or response.
// This is used in requests including InternalInvokeRequestStream.
type StreamPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data sent in the chunk.
	// The amount of data included in each chunk is up to the discretion of the sender, and can be empty.
	// Additionally, the amount of data doesn't need to be fixed and subsequent messages can send more, or less, data.
	// Receivers must not make assumptions about the number of bytes they'll receive in each chunk.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Sequence number. This is a counter that starts from 0 and increments by 1 on each chunk sent.
	Seq           uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPayload) Reset() {
	*x = StreamPayload{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPayload) ProtoMessage() {}

func (x *StreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPayload.ProtoReflect.Descriptor instead.
func (*StreamPayload) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *StreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamPayload) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// StateItem represents state key, value, and additional options to save state.
type StateItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The state key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Required. The state data for key
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The entity tag which represents the specific version of data.
	// The exact ETag format is defined by the corresponding data store.
	Etag *Etag `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	// The metadata which will be passed to state store component.
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Options for concurrency and consistency to save the state.
	Options       *StateOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateItem) Reset() {
	*x = StateItem{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateItem) ProtoMessage() {}

func (x *StateItem) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateItem.ProtoReflect.Descriptor instead.
func (*StateItem) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *StateItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateItem) GetEtag() *Etag {
	if x != nil {
		return x.Etag
	}
	return nil
}

func (x *StateItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StateItem) GetOptions() *StateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Etag represents a state item version
type Etag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value sets the etag value
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etag) Reset() {
	*x = Etag{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etag) ProtoMessage() {}

func (x *Etag) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etag.ProtoReflect.Descriptor instead.
func (*Etag) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Etag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// StateOptions configures concurrency and consistency for state operations
type StateOptions struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Concurrency   StateOptions_StateConcurrency `protobuf:"varint,1,opt,name=concurrency,proto3,enum=dapr.proto.common.v1.StateOptions_StateConcurrency" json:"concurrency,omitempty"`
	Consistency   StateOptions_StateConsistency `protobuf:"varint,2,opt,name=consistency,proto3,enum=dapr.proto.common.v1.StateOptions_StateConsistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateOptions) Reset() {
	*x = StateOptions{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateOptions) ProtoMessage() {}

func (x *StateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateOptions.ProtoReflect.Descriptor instead.
func (*StateOptions) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *StateOptions) GetConcurrency() StateOptions_StateConcurrency {
	if x != nil {
		return x.Concurrency
	}
	return StateOptions_CONCURRENCY_UNSPECIFIED
}

func (x *StateOptions) GetConsistency() StateOptions_StateConsistency {
	if x != nil {
		return x.Consistency
	}
	return StateOptions_CONSISTENCY_UNSPECIFIED
}

// ConfigurationItem represents all the configuration with its name(key).
type ConfigurationItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The value of configuration item.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Version is response only and cannot be fetched. Store is not expected to keep all versions available
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// the metadata which will be passed to/from configuration store component.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationItem) Reset() {
	*x = ConfigurationItem{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationItem) ProtoMessage() {}

func (x *ConfigurationItem) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationItem.ProtoReflect.Descriptor instead.
func (*ConfigurationItem) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigurationItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigurationItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigurationItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// JobFailurePolicy defines the policy to apply when a job fails to trigger.
type JobFailurePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policy is the policy to apply when a job fails to trigger.
	//
	// Types that are valid to be assigned to Policy:
	//
	//	*JobFailurePolicy_Drop
	//	*JobFailurePolicy_Constant
	Policy        isJobFailurePolicy_Policy `protobuf_oneof:"policy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailurePolicy) Reset() {
	*x = JobFailurePolicy{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailurePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailurePolicy) ProtoMessage() {}

func (x *JobFailurePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailurePolicy.ProtoReflect.Descriptor instead.
func (*JobFailurePolicy) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *JobFailurePolicy) GetPolicy() isJobFailurePolicy_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *JobFailurePolicy) GetDrop() *JobFailurePolicyDrop {
	if x != nil {
		if x, ok := x.Policy.(*JobFailurePolicy_Drop); ok {
			return x.Drop
		}
	}
	return nil
}

func (x *JobFailurePolicy) GetConstant() *JobFailurePolicyConstant {
	if x != nil {
		if x, ok := x.Policy.(*JobFailurePolicy_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

type isJobFailurePolicy_Policy interface {
	isJobFailurePolicy_Policy()
}

type JobFailurePolicy_Drop struct {
	Drop *JobFailurePolicyDrop `protobuf:"bytes,1,opt,name=drop,proto3,oneof"`
}

type JobFailurePolicy_Constant struct {
	Constant *JobFailurePolicyConstant `protobuf:"bytes,2,opt,name=constant,proto3,oneof"`
}

func (*JobFailurePolicy_Drop) isJobFailurePolicy_Policy() {}

func (*JobFailurePolicy_Constant) isJobFailurePolicy_Policy() {}

// JobFailurePolicyDrop is a policy which drops the job tick when the job fails to trigger.
type JobFailurePolicyDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailurePolicyDrop) Reset() {
	*x = JobFailurePolicyDrop{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailurePolicyDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailurePolicyDrop) ProtoMessage() {}

func (x *JobFailurePolicyDrop) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailurePolicyDrop.ProtoReflect.Descriptor instead.
func (*JobFailurePolicyDrop) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{9}
}

// JobFailurePolicyConstant is a policy which retries the job at a consistent interval when the job fails to trigger.
type JobFailurePolicyConstant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interval is the constant delay to wait before retrying the job.
	Interval *durationpb.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// max_retries is the optional maximum number of retries to attempt before giving up.
	// If unset, the Job will be retried indefinitely.
	MaxRetries    *uint32 `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3,oneof" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailurePolicyConstant) Reset() {
	*x = JobFailurePolicyConstant{}
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailurePolicyConstant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailurePolicyConstant) ProtoMessage() {}

func (x *JobFailurePolicyConstant) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_common_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailurePolicyConstant.ProtoReflect.Descriptor instead.
func (*JobFailurePolicyConstant) Descriptor() ([]byte, []int) {
	return file_dapr_proto_common_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *JobFailurePolicyConstant) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *JobFailurePolicyConstant) GetMaxRetries() uint32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

var File_dapr_proto_common_v1_common_proto protoreflect.FileDescriptor

const file_dapr_proto_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"!dapr/proto/common/v1/common.proto\x12\x14dapr.proto.common.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xe3\x01\n" +
	"\rHTTPExtension\x12<\n" +
	"\x04verb\x18\x01 \x01(\x0e2(.dapr.proto.common.v1.HTTPExtension.VerbR\x04verb\x12 \n" +
	"\vquerystring\x18\x02 \x01(\tR\vquerystring\"r\n" +
	"\x04Verb\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04HEAD\x10\x02\x12\b\n" +
	"\x04POST\x10\x03\x12\a\n" +
	"\x03PUT\x10\x04\x12\n" +
	"\n" +
	"\x06DELETE\x10\x05\x12\v\n" +
	"\aCONNECT\x10\x06\x12\v\n" +
	"\aOPTIONS\x10\a\x12\t\n" +
	"\x05TRACE\x10\b\x12\t\n" +
	"\x05PATCH\x10\t\"\xc0\x01\n" +
	"\rInvokeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12J\n" +
	"\x0ehttp_extension\x18\x04 \x01(\v2#.dapr.proto.common.v1.HTTPExtensionR\rhttpExtension\"]\n" +
	"\x0eInvokeResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"5\n" +
	"\rStreamPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\xa9\x02\n" +
	"\tStateItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12.\n" +
	"\x04etag\x18\x03 \x01(\v2\x1a.dapr.proto.common.v1.EtagR\x04etag\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.dapr.proto.common.v1.StateItem.MetadataEntryR\bmetadata\x12<\n" +
	"\aoptions\x18\x05 \x01(\v2\".dapr.proto.common.v1.StateOptionsR\aoptions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\x04Etag\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x89\x03\n" +
	"\fStateOptions\x12U\n" +
	"\vconcurrency\x18\x01 \x01(\x0e23.dapr.proto.common.v1.StateOptions.StateConcurrencyR\vconcurrency\x12U\n" +
	"\vconsistency\x18\x02 \x01(\x0e23.dapr.proto.common.v1.StateOptions.StateConsistencyR\vconsistency\"h\n" +
	"\x10StateConcurrency\x12\x1b\n" +
	"\x17CONCURRENCY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONCURRENCY_FIRST_WRITE\x10\x01\x12\x1a\n" +
	"\x16CONCURRENCY_LAST_WRITE\x10\x02\"a\n" +
	"\x10StateConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONSISTENCY_EVENTUAL\x10\x01\x12\x16\n" +
	"\x12CONSISTENCY_STRONG\x10\x02\"\xd3\x01\n" +
	"\x11ConfigurationItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12Q\n" +
	"\bmetadata\x18\x03 \x03(\v25.dapr.proto.common.v1.ConfigurationItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x10JobFailurePolicy\x12@\n" +
	"\x04drop\x18\x01 \x01(\v2*.dapr.proto.common.v1.JobFailurePolicyDropH\x00R\x04drop\x12L\n" +
	"\bconstant\x18\x02 \x01(\v2..dapr.proto.common.v1.JobFailurePolicyConstantH\x00R\bconstantB\b\n" +
	"\x06policy\"\x16\n" +
	"\x14JobFailurePolicyDrop\"\x87\x01\n" +
	"\x18JobFailurePolicyConstant\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12$\n" +
	"\vmax_retries\x18\x02 \x01(\rH\x00R\n" +
	"maxRetries\x88\x01\x01B\x0e\n" +
	"\f_max_retriesB\xdf\x01\n" +
	"\x18com.dapr.proto.common.v1B\vCommonProtoP\x01ZCgithub.com/dapr/go-sdk/internal/proto/dapr/proto/common/v1;commonv1\xa2\x02\x03DPC\xaa\x02\x14Dapr.Proto.Common.V1\xca\x02\x14Dapr\\Proto\\Common\\V1\xe2\x02 Dapr\\Proto\\Common\\V1\\GPBMetadata\xea\x02\x17Dapr::Proto::Common::V1b\x06proto3"

var (
	file_dapr_proto_common_v1_common_proto_rawDescOnce sync.Once
	file_dapr_proto_common_v1_common_proto_rawDescData []byte
)

func file_dapr_proto_common_v1_common_proto_rawDescGZIP() []byte {
	file_dapr_proto_common_v1_common_proto_rawDescOnce.Do(func() {
		file_dapr_proto_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dapr_proto_common_v1_common_proto_rawDesc), len(file_dapr_proto_common_v1_common_proto_rawDesc)))
	})
	return file_dapr_proto_common_v1_common_proto_rawDescData
}

var file_dapr_proto_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dapr_proto_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dapr_proto_common_v1_common_proto_goTypes = []any{
	(HTTPExtension_Verb)(0),            // 0: dapr.proto.common.v1.HTTPExtension.Verb
	(StateOptions_StateConcurrency)(0), // 1: dapr.proto.common.v1.StateOptions.StateConcurrency
	(StateOptions_StateConsistency)(0), // 2: dapr.proto.common.v1.StateOptions.StateConsistency
	(*HTTPExtension)(nil),              // 3: dapr.proto.common.v1.HTTPExtension
	(*InvokeRequest)(nil),              // 4: dapr.proto.common.v1.InvokeRequest
	(*InvokeResponse)(nil),             // 5: dapr.proto.common.v1.InvokeResponse
	(*StreamPayload)(nil),              // 6: dapr.proto.common.v1.StreamPayload
	(*StateItem)(nil),                  // 7: dapr.proto.common.v1.StateItem
	(*Etag)(nil),                       // 8: dapr.proto.common.v1.Etag
	(*StateOptions)(nil),               // 9: dapr.proto.common.v1.StateOptions
	(*ConfigurationItem)(nil),          // 10: dapr.proto.common.v1.ConfigurationItem
	(*JobFailurePolicy)(nil),           // 11: dapr.proto.common.v1.JobFailurePolicy
	(*JobFailurePolicyDrop)(nil),       // 12: dapr.proto.common.v1.JobFailurePolicyDrop
	(*JobFailurePolicyConstant)(nil),   // 13: dapr.proto.common.v1.JobFailurePolicyConstant
	nil,                                // 14: dapr.proto.common.v1.StateItem.MetadataEntry
	nil,                                // 15: dapr.proto.common.v1.ConfigurationItem.MetadataEntry
	(*anypb.Any)(nil),                  // 16: google.protobuf.Any
	(*durationpb.Duration)(nil),        // 17: google.protobuf.Duration
}
var file_dapr_proto_common_v1_common_proto_depIdxs = []int32{
	0,  // 0: dapr.proto.common.v1.HTTPExtension.verb:type_name -> dapr.proto.common.v1.HTTPExtension.Verb
	16, // 1: dapr.proto.common.v1.InvokeRequest.data:type_name -> google.protobuf.Any
	3,  // 2: dapr.proto.common.v1.InvokeRequest.http_extension:type_name -> dapr.proto.common.v1.HTTPExtension
	16, // 3: dapr.proto.common.v1.InvokeResponse.data:type_name -> google.protobuf.Any
	8,  // 4: dapr.proto.common.v1.StateItem.etag:type_name -> dapr.proto.common.v1.Etag
	14, // 5: dapr.proto.common.v1.StateItem.metadata:type_name -> dapr.proto.common.v1.StateItem.MetadataEntry
	9,  // 6: dapr.proto.common.v1.StateItem.options:type_name -> dapr.proto.common.v1.StateOptions
	1,  // 7: dapr.proto.common.v1.StateOptions.concurrency:type_name -> dapr.proto.common.v1.StateOptions.StateConcurrency
	2,  // 8: dapr.proto.common.v1.StateOptions.consistency:type_name -> dapr.proto.common.v1.StateOptions.StateConsistency
	15, // 9: dapr.proto.common.v1.ConfigurationItem.metadata:type_name -> dapr.proto.common.v1.ConfigurationItem.MetadataEntry
	12, // 10: dapr.proto.common.v1.JobFailurePolicy.drop:type_name -> dapr.proto.common.v1.JobFailurePolicyDrop
	13, // 11: dapr.proto.common.v1.JobFailurePolicy.constant:type_name -> dapr.proto.common.v1.JobFailurePolicyConstant
	17, // 12: dapr.proto.common.v1.JobFailurePolicyConstant.interval:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_dapr_proto_common_v1_common_proto_init() }
func file_dapr_proto_common_v1_common_proto_init() {
	if File_dapr_proto_common_v1_common_proto != nil {
		return
	}
	file_dapr_proto_common_v1_common_proto_msgTypes[8].OneofWrappers = []any{
		(*JobFailurePolicy_Drop)(nil),
		(*JobFailurePolicy_Constant)(nil),
	}
	file_dapr_proto_common_v1_common_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapr_proto_common_v1_common_proto_rawDesc), len(file_dapr_proto_common_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dapr_proto_common_v1_common_proto_goTypes,
		DependencyIndexes: file_dapr_proto_common_v1_common_proto_depIdxs,
		EnumInfos:         file_dapr_proto_common_v1_common_proto_enumTypes,
		MessageInfos:      file_dapr_proto_common_v1_common_proto_msgTypes,
	}.Build()
	File_dapr_proto_common_v1_common_proto = out.File
	file_dapr_proto_common_v1_common_proto_goTypes = nil
	file_dapr_proto_common_v1_common_proto_depIdxs = nil
}
